variables:
  DEPLOYMENT_NAME: gitlab-poc
  CLUSTER_NAME: gitlab-poc
  DOCKER_REGISTRY: 758596141641.dkr.ecr.us-east-1.amazonaws.com/$DEPLOYMENT_NAME
  REGION: us-east-1
  CI_COMMIT_TAG: lastest

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache curl jq python3 py-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email --region $REGION)
    - docker build -t $DOCKER_REGISTRY:$CI_COMMIT_TAG .
    - docker push $DOCKER_REGISTRY:$CI_COMMIT_TAG
  only:
    - master
