variables:
  DEPLOYMENT_NAME: gitlab-poc
  CLUSTER_NAME: gitlab-poc
  DOCKER_REGISTRY: 758596141641.dkr.ecr.us-east-1.amazonaws.com/$DEPLOYMENT_NAME
  REGION: us-east-1
  CI_COMMIT_TAG: latest

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache curl jq python3 py-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email --region $REGION)
    - docker build -t $DOCKER_REGISTRY:$CI_COMMIT_TAG .
    - docker push $DOCKER_REGISTRY:$CI_COMMIT_TAG
  only:
    - master

.kubectl_config: &kubectl_config
  - aws eks --region $REGION update-kubeconfig --name $CLUSTER_NAME

deploy_staging:
  image: docker.io/sulemanhasib43/eks:latest
  stage: deploy
  variables:
    K8S_NAMESPACE: gitlab-managed-apps
  before_script: *kubectl_config
  script:
    - kubectl version
    - kubectl -n $K8S_NAMESPACE patch deployment hello-world-php -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$DEPLOYMENT_NAME"'","image":"'"$DOCKER_REGISTRY:$CI_COMMIT_TAG"'"}]}}}}'
  environment:
    name: staging
    url: http://alpha.rocketmat.com
  only:
    - master